"""create packages table

Revision ID: e4c24d800f53
Revises: 
Create Date: 2022-07-14 11:26:55.538934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c24d800f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('sender', sa.String(length=255), nullable=True))
    op.alter_column('packages', 'recipient',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('packages', 'origin',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('packages', 'destination',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('packages', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('packages', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('packages', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('packages', 'destination',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('packages', 'origin',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('packages', 'recipient',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('packages', 'sender')
    # ### end Alembic commands ###
